---
title: "布朗运动"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## T1
```{r 1.1}
rm(list = ls())
set.seed(18)
bm=matrix(0,5001,100);
t=seq(0,2,by = 0.0004)
for(j in 1:100){
  eps=rnorm(5000,0,0.02)
  for(i in 2:5001){
    bm[i,j]=bm[i-1,j]+eps[i-1];
  }
}
matplot(t,bm[,1:3], type = 'l', lty = 1, ylab = "BM轨道", xlab = "Time",
        col = c('blue','black','red'))
```
```{r 1.2}
matplot(t,bm, type = 'l', lty = 1, ylab = "BM轨道", xlab = "Time")

## 正态分布95%置信区间[-1.96*sd,1.96*sd]
matplot(t,bm, type = 'l', lty = 1, ylab = "BM轨道", xlab = "Time",col = 'gray')
points(t,1.96*sqrt(t),type = 'l', lwd=2, lty=2, col = 'black')
points(t,-1.96*sqrt(t),type = 'l', lwd=2, lty=2, col = 'black')
```

## T2
```{r 2.0}
rm(list = ls())
alpha=2;v=2;sig=1;x0=1;dt=4e-4
set.seed(18)
x=matrix(0,5001,200);
t=seq(0,2,by = dt)
for(j in 1:200){
  x[1,j]=x0;
  eps=rnorm(5000,0,0.02)
  for(i in 2:5001){
    x[i,j]=x[i-1,j]+alpha*(v-x[i-1,j])*dt+eps[i-1]*sig;
  }
}
```
```{r 2.1-2}
matplot(t, x[,1:3], type = 'l', lty = 1, ylab = "X过程", xlab = "Time")
##多图比较
matplot(t, x[,1:100], type = 'l', ylab = "X过程", xlab = "Time", col = 'gray')
#title("σ=100")
matplot(t, x[,1:100], type = 'l', ylab = "X过程", xlab = "Time", col = 'gray')
points(t,v-(v-x0)*exp(-alpha*t), type = 'l', lty = 2)
```
```{r 2.3}
##蒙特卡洛
mx1=rep(0,200);varx1=rep(0,200)
for(i in 2:200){
  mx1[i]=mean(x[2501,1:i]);
  varx1[i]=var(x[2501,1:i]);
}
plot(mx1,type = 'l',ylab = 'Monte-Carlo期望', xlab = "计算次数N")
plot(varx1,type = 'l',ylab = 'Monte-Carlo方差', xlab = "计算次数N")

##结果
ex1=v-(v-x0)*exp(-alpha);ex1 ##理论值
mx1[200];varx1[200];

##2-sig准则(95%置信),绘制置信范围
matplot(t, x, type = 'l', ylab = "X过程", xlab = "Time",col = 'gray')
mx=apply(x,1,mean);sdx=apply(x,1,sd)
points(t,mx, type = 'l', lty = 5)
points(t,mx+2*sdx, type = 'l', lty = 2, col = 'red')
points(t,mx-2*sdx, type = 'l', lty = 2, col = 'red')
```

## T3
```{r 3.0}
rm(list = ls())
alpha=10;v=2;th=100;sig=1;sig1=1;sig2=1;x0=10;s0=0;dt=4e-4
set.seed(18)
x=matrix(0,5001,200);s=matrix(0,5001,200);
t=seq(0,2,by = dt)
for(j in 1:200){
  x[1,j]=x0;s[1,j]=s0
  eps1=rnorm(5000,0,0.02)
  eps2=rnorm(5000,0,0.02)
  for(i in 2:5001){
    x[i,j]=x[i-1,j]+alpha*(v-x[i-1,j])*dt+eps1[i-1]*sig;
    s[i,j]=s[i-1,j]+th*(x[i-1,j]-s[i-1,j])*dt+eps1[i-1]*sig1+eps2[i-1]*sig2
  }
}
```
```{r t3.1-2}
matplot(t, s[,1:3], type = 'l', lty = 1, ylab = "S过程", xlab = "Time")
##多图比较
matplot(t, s[,1:100], type = 'l', lty = 1, ylab = "S过程", xlab = "Time", col="gray")
title("σ1=1,σ2=1")
```
```{r t3.2.2}
matplot(t, s[,1:100], type = 'l', lty = 1, ylab = "S过程", xlab = "Time",col = 'gray')
points(t,v-(v-s0)*exp(-th*t), type = 'l', lty = 2)
title("α=10")
points(t,v-(v-x0)*exp(-alpha*t), type = 'l', lty = 2, col="red")

#matplot(t, x[,1:100], type = 'l', ylab = "X过程", xlab = "Time",col = 'gray')
#points(t,v-(v-x0)*exp(-alpha*t), type = 'l', lty = 2,col = "red")
```
```{r 3.3}
##蒙特卡洛
ms1=rep(0,200);vars1=rep(0,200)
for(i in 1:200){
  ms1[i]=mean(s[2501,1:i]);
  vars1[i]=var(s[2501,1:i]);
}
plot(ms1,type = 'l',ylab = 'Monte-Carlo期望', xlab = "计算次数N")
plot(vars1,type = 'l',ylab = 'Monte-Carlo方差', xlab = "计算次数N")

##结果
ms1[200];vars1[200]

##2-sig准则(95%置信),绘制置信范围
matplot(t, s, type = 'l', ylab = "X过程", xlab = "Time",col = 'gray')
ms=apply(s,1,mean);sds=apply(s,1,sd)
points(t,ms, type = 'l', lty = 5)
points(t,ms+2*sds, type = 'l', lty = 2, col = 'red')
points(t,ms-2*sds, type = 'l', lty = 2, col = 'red')
```
